// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'benefit': string;
  'bottle': string;
  'brend': string;
  'eightBubleAnimation': string;
  'firstBlueBubble': string;
  'firstBubleAnimation': string;
  'firstLetter': string;
  'firstPinkBubble': string;
  'fiveBlueBubble': string;
  'fiveBubleAnimation': string;
  'fourthBlueBubble': string;
  'fourthBubleAnimation': string;
  'keyMessage': string;
  'mainFrame': string;
  'more': string;
  'secondBlueBubble': string;
  'secondBubleAnimation': string;
  'secondLetter': string;
  'secondPinkBubble': string;
  'sevenBubleAnimation': string;
  'sixBubleAnimation': string;
  'thirdBlueBubble': string;
  'thirdBubleAnimation': string;
  'thirdPinkBubble': string;
}
export const cssExports: CssExports;
export default cssExports;
