// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activePopint': string;
  'first': string;
  'firstPoint': string;
  'five': string;
  'fourth': string;
  'keyMessage': string;
  'next': string;
  'prev': string;
  'second': string;
  'secondPoint': string;
  'six': string;
  'text': string;
  'third': string;
}
export const cssExports: CssExports;
export default cssExports;
