// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main': string;
  'nav_home': string;
  'nav_project': string;
  'unselectable': string;
}
export const cssExports: CssExports;
export default cssExports;
