// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bacteriaUnderNav': string;
  'centerBigBacteria': string;
  'hello': string;
  'leftBacteria': string;
  'mainFrame': string;
  'nonComercial': string;
  'pinkSperm': string;
  'rightBacteria': string;
  'rightBacteriaMove': string;
  'rightSmallBacteria': string;
  'rightSmallBacteriaMove': string;
  'whatNext': string;
}
export const cssExports: CssExports;
export default cssExports;
