// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'description': string;
  'emm': string;
  'extraScroll': string;
  'frame': string;
  'mainFrame': string;
  'message': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
